### ISSUE TITLE
Main task: Project setup

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/dummie-repo#169]
- [x] EC-rika-project/dummie-repo#170
- [x] EC-rika-project/dummie-repo#171
- [x] EC-rika-project/dummie-repo#172
- [x] EC-rika-project/dummie-repo#173
- [x] EC-rika-project/dummie-repo#174
- [x] EC-rika-project/dummie-repo#175
- [ ] EC-rika-project/dummie-repo#182
- [ ] EC-rika-project/dummie-repo#176
- [x] EC-rika-project/dummie-repo#177
- [ ] EC-rika-project/dummie-repo#183
- [x] EC-rika-project/dummie-repo#178
- [ ] EC-rika-project/dummie-repo#184
- [x] EC-rika-project/dummie-repo#179
- [ ] EC-rika-project/dummie-repo#185
- [ ] EC-rika-project/WebApp-RIKA-WIN23#40
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#17
- [ ] EC-rika-project/dummie-repo#200
- [ ] EC-rika-project/dummie-repo#201
- [ ] EC-rika-project/dummie-repo#202
- [ ] EC-rika-project/WebApp-RIKA-WIN23#84
- [ ] EC-rika-project/API-Orders-RIKA-WIN23#3
- [ ] EC-rika-project/API-Products-RIKA-WIN23#24
- [ ] EC-rika-project/API-Users-RIKA-WIN23#12
